wallpaper="$HOME/.config/hypr/wallpapers/tTIlCNT.png"
focuswallpaper="$HOME/.config/hypr/wallpapers/dark.png"

homewifi="Eendje"
interface="wg0"
homeserver="pipi4@192.168.11.128"

save_dir="$HOME/Videos/screenrecord"
