theme:
  background-color: 0 1 16
  primary-color: 43 59 81
  positive-color: 61 66 44
  negative-color: 6 96 59
pages:
  - name: Home
    # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
    hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 12h
            feeds:
              - url: https://archlinux.org/feeds/news
                title: archlinux.org
              - url: https://selfh.st/rss/
                title: selfh.st
                limit: 4
              - url: https://ciechanow.ski/atom.xml
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadeed

          # - type: twitch-channels
          #   channels:
          #     - theprimeagen
          #     - j_blow
          #     - piratesoftware
          #     - cohhcarnage
          #     - christitustech
          #     - EJ_SA

      - size: full
        widgets:
          - type: group
            widgets:
              - type: hacker-news
              - type: lobsters

          - type: videos
            channels:
              - UCRcgy6GzDeccI7dkbbBna3Q # Lemmino
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCwHwDuNd9lCdA7chyyquDXw # Bread on Penguins
              - UC7YOGHUfC1Tb6E4pudI9STA # Mental Outlaw
              - UCZXW8E1__d5tZb-wLFOt8TQ # Bog

          - type: group
            widgets:
              - type: reddit
                subreddit: technology
                show-thumbnails: true
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true

      - size: small
        widgets:
          - type: weather
            location: The Hague
            units: metric # alternatively "imperial"
            hour-format: 24h # alternatively "24h"
            # Optionally hide the location from being displayed in the widget
            # hide-location: true

          - type: markets
            markets:
              - symbol: XMR-USD
                name: Monero
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft

          # - type: releases
          #   cache: 1d
          #   # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          #   # read-only token from your Github account settings and use it here to increase the limit.
          #   # token: ...
          #   repositories:
          #     - glanceapp/glance
          #     - go-gitea/gitea
          #     - immich-app/immich
          #     - syncthing/syncthing

  # Add more pages here:
  # - name: Your page name
  #   columns:
  #     - size: small
  #       widgets:
  #         # Add widgets here

  #     - size: full
  #       widgets:
  #         # Add widgets here

  #     - size: small
  #       widgets:
  #         # Add widgets here

